/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Amazon S3',
      items: [
        'amazon-s3/s3-select',
        'amazon-s3/58a2f',
        'amazon-s3/01161',
      ],
    },
    {
      type: 'category',
      label: '대학 고객을 위한 AWS 길라잡이',
      items: [
        'aws/aws',
        'aws/otp',
        'aws/28f0b',
        'aws/cloud9',
        'aws/ec2',
        'aws/ami-gwl',
        'aws/d61e4',
        'aws/aws-cli',
        'aws/d2dde',
        'aws/40008',
        'aws/ec2-ami',
        'aws/ec2-BcK',
        'aws/ami',
        'aws/hail-on-ec2',
        'aws/amazon-lightsail-for-research',
        'aws/research-and-engineering-studio-on-aws',
        'aws/dc6a6',
        'aws/d82c8',
        'aws/812b4',
        'aws/rstudio',
      ],
    },
    {
      type: 'category',
      label: 'Omics on AWS',
      items: [
        'omics-on-aws/aws-healthomics',
        'omics-on-aws/nf-core-scrnaseq',
        'omics-on-aws/nf-core-rnaseq',
        'omics-on-aws/nf-core-spatialvi',
        'omics-on-aws/wdl-hifi-human-wgs-wdl',
        'omics-on-aws/aws-healthomics-fastq-to-vcf-annotation',
        'omics-on-aws/aws-healthomics-storage',
        'omics-on-aws/aws-healthomics-annotation',
        'omics-on-aws/aws-healthomics-troubleshooting',
        'omics-on-aws/65b9e',
        'omics-on-aws/aws-healthomics-run-analyzer-run-1910249',
        'omics-on-aws/amazon-emr-on-ec2',
        'omics-on-aws/aws-glue',
        'omics-on-aws/hail-with-amazon-emr-notebook',
        'omics-on-aws/quickstart-hail-korean',
        'omics-on-aws/quickstart-hail-english',
        'omics-on-aws/a597e',
        'omics-on-aws/store-multimodal-data-with-purpose-built-health-ai-services',
        'omics-on-aws/amazon-genomics-cli-vDj',
        'omics-on-aws/example-code',
      ],
    },
    {
      type: 'category',
      label: 'AWS Batch',
      items: [
        'aws-batch/tagging-w-nextflow',
        'aws-batch/troubleshooting-for-aws-batch-nextflow',
      ],
    },
    {
      type: 'category',
      label: 'AWS BLAST Performance Testing',
      items: [
        'aws-blast-performance-testing/26657',
        'aws-blast-performance-testing/cost-analysis',
        'aws-blast-performance-testing/ebs',
        'aws-blast-performance-testing/efs-vs-fsx-for-lustre',
        'aws-blast-performance-testing/ebs-snapshot',
      ],
    },
  ],
};

module.exports = sidebars;
